spring.application.name=gateway

server.port=8080
app.jwt.secret=VGhpcy1Jcy1BLVZlcnktU2VjdXJlLVNlY3JldC1LZXktRm9yLUpXVC1BcGktQXV0aGVudGljYXRpb24=

spring.cloud.gateway.routes[0].id=doctor-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/doctors

spring.cloud.gateway.routes[0].filters[0]=JwtVlidationFilter
